<?php

/**
 * @file
 * Contains training_overview.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function training_overview_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the training_overview module.
    case 'help.page.training_overview':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function training_overview_theme() {
  return [
    'training_overview' => [
      'render element' => 'children',
    ],
  ];
}
