<?php

/**
 * @file
 * Provides an employee overview entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\employee_overview\Event\EmployeeOverviewEvent;

/**
 * Implements hook_theme().
 */
function employee_overview_theme() {
  return [
    'employee_overview' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for employee overview templates.
 *
 * Default template: employee-overview.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the employee overview information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_employee_overview(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

function employee_overview_user_login($account) {
  // Instantiate the User event.
  $event = new EmployeeOverviewEvent($account);

  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(EmployeeOverviewEvent::EVENT_NAME, $event);
}


/**
 * Implements hook_theme().
 */
function olivero_theme($existing, $type, $theme, $path): array
{
  return [
    'exercise_block' => [
      'template' => 'employee-overview',
    ],
  ];
}
