<?php

/**
 * @file
 * Provides an employee overview entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function employee_overview_theme() {
  return [
    'employee_overview' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for employee overview templates.
 *
 * Default template: employee-overview.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the employee overview information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_employee_overview(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
